"""empty message

Revision ID: 9a9aea39b90d
Revises: bba716a6c83a
Create Date: 2020-09-28 11:10:05.084448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9aea39b90d'
down_revision = 'bba716a6c83a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Venue_area_fkey', 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'area',)
    op.drop_table('Area')
    op.alter_column('Artist', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'Artist', ['name'])
    op.create_unique_constraint(None, 'Venue', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('area', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Venue_area_fkey', 'Venue', 'Area', ['area'], ['id'])
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    op.alter_column('Artist', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('Area',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Area_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Area_pkey')
    )
    # ### end Alembic commands ###
